version: "3.3"
networks:
  vaccinet:
    driver: bridge

services:
  chromedriver:
    container_name: vacci-scraper
    image: selenium/standalone-chrome
    restart: unless-stopped
    environment:
      - SE_OPTS=-timeout 86400 -browserTimeout 86400
    ports:
      - "4444:4444"
    networks:
      - vaccinet


  scraper:
    container_name: vacci-script
    #image: rutgersmit/vacci-watcher
    build: .
    restart: unless-stopped
    command: python3 watcher.py
    environment: 
      - TELEGRAM_CHATID=
      - TELEGRAM_TOKEN=
      - INTERVAL=60
      - VACCINATION_CITY=
      - REMOTE_SELENIUM_HOSTNAME=vacci-scraper
    volumes: 
      - /etc/localtime:/etc/localtime
      - ~/log:/app/log
    links:
      - chromedriver:selenium
    depends_on:
      - chromedriver
    networks:
      - vaccinet

